# Generated by Django 5.2.5 on 2025-08-28 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="genre",
            old_name="dascription",
            new_name="description",
        ),
    ]
