# Generated by Django 5.2.5 on 2025-09-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_dascription_genre_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
